# Generated by Django 5.0.4 on 2024-05-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='description',
            field=models.TextField(blank=True, default='Store Admin', null=True),
        ),
    ]
