# Generated by Django 5.0.4 on 2024-05-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_admin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.CharField(default='kpr1prPprFprOprFprJprDpr2pr9prvprDprSprwprGpr6prJpr0prWprK', max_length=20),
        ),
    ]
