# Generated by Django 5.0.4 on 2024-05-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='vadmAadmJadmaadmdadmtadmuadmiadmladmMadmzadmSadmUadmyadm2admladmhadmhadmZadmD', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='cid',
            field=models.CharField(default='3catpcatWcatycatjcatJcatScatTcatXcatWcatUcatDcatGcatBcatscattcatlcatqcatOcatY', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='yprFprRprApr4priprLpryprCprUprLprFprrprZprvprqprXprfpr5pr0', max_length=20),
        ),
    ]
