# Generated by Django 5.0.4 on 2024-05-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_admin_aid_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='kadmgadmOadmLadm5admXadm7admdadm1admX', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='QcatQcatvcat9catJcatucatvcatycatacatZ', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='BprOprdprcprqprBprspr9prnprQ', max_length=100),
        ),
    ]
