# Generated by Django 5.0.4 on 2024-05-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_admin_aid_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='aadm8admhadmGadmQadmNadmaadmuadmbadmU', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='0cat2catPcatmcatScatGcatIcatzcattcato', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='pprUpr0prVprdprVprWpriprXpry', max_length=100),
        ),
    ]
