# Generated by Django 5.0.4 on 2024-05-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_admin_aid_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admp2knOpc6BYTYkIbQudlw', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='cataFb9Nj8Pipj81v3IUn12', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='praNLLQao2yIdT6TMXyABB', max_length=20),
        ),
    ]
