# Generated by Django 5.0.4 on 2024-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_admin_aid_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admI8IEOmbT3eUnG4tORsUT', max_length=23),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catwJOqXXHSG3WJJJLlWz5j', max_length=23),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='pr4YLs4X6N8fjmHxsprHOx', max_length=22),
        ),
    ]
