# Generated by Django 5.0.4 on 2024-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_admin_aid_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admWaPa4aWaGaVaxaOa7a3aiacanaSawa9a9a5a5aJ', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catWcvc6cEctcOc1cvc7cbcTcVcfcOc4cocdcMcCc6', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='prppJpEp2p9p3pXpbp3p5psplpMp5pWpcpYpGp9pZ', max_length=30),
        ),
    ]
