# Generated by Django 5.0.4 on 2024-05-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_admin_aid_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admNasapaba8a4a8a1aHaU', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catKcAcMcGcxc1c9cncwcW', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='pr6pspIpnpkpCpApYpTpC', max_length=20),
        ),
    ]
