# Generated by Django 5.0.4 on 2024-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_admin_aid_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admnEFESEpEQEPEoEwEGEIEwExEDEyE1EjEfE4EvE5', max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catlJVJaJlJbJpJGJJJSJXJyJ9JnJvJjJCJkJSJOJ7', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='proSCYChCHCKCsC7CPCQCnCrC6CDCnCoC8CICHCIC3', max_length=40),
        ),
    ]
