# Generated by Django 5.0.4 on 2024-05-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_admin_aid_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admuA5A5ARAJACAQAmARAKAZAgAPAAA6AkAQAlAIAZ', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catOQEQIQ0QLQGQRQYQIQOQQQkQrQ2QYQHQXQzQXQ9', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='prowi9i3iGiViZijijiLiuiTiuizijipiOiVi0iEiI', max_length=50),
        ),
    ]
