# Generated by Django 5.0.4 on 2024-05-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_admin_cover_image_alter_admin_aid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admTG2GCGmG8GtGcGJGIGHGSG4GXGCGXGpGMGSGAG2', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catObNbxbPbqb5brbAb3bYbZblbTbObjbZb7bXb7b4', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='proREVEZEoE5EYETEOEvEBEqE7EPE5EAEYESEkE1El', max_length=50),
        ),
    ]
