# Generated by Django 5.0.4 on 2024-05-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_admin_aid_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admciuiKiaikixi6i4iUiFiGiSirimiUiXiXiMiniJ', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catzzqzFzOz6znzHzQzrzCzAznzRzazWzXzzzFzvza', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='pro3TtTbT6TzTXTjTyTdTMT5TaTMTDTPTuT6TzTETc', max_length=50),
        ),
    ]
