# Generated by Django 5.0.4 on 2024-05-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_admin_aid_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_weight',
            field=models.FloatField(default=8, max_length=3),
        ),
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admKiciCi4iuiiiciJi7iviiiniMiSiwiIi3iOiWif', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catnApAGAWA0AEAGACApA1A9A7AIATAVAqADADAxAc', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='progjYj6jzjyjkjPjdjejrjPjrjujkj2jdjYjGjOjc', max_length=50),
        ),
    ]
