# Generated by Django 5.0.4 on 2024-05-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_total_weight_alter_admin_aid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admbCTCoCcCqCDCpCpCgC8ChCfCoC2C2CPCPCLC5Co', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catyqEqJq1qLqyqMqgqNq7qEqzqIq5qKqhqyqXq5qa', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='proXiGiDiWiUifivioi6iUi5ieiDioidiSiKiTiriI', max_length=50),
        ),
    ]
