# Generated by Django 5.0.4 on 2024-05-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_product_life_remove_product_mfd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_count',
        ),
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admnqkqxqvqHqfqSqIqAqxqTqlqdq4qpqiqbqyqDqR', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catgyfyrytyXyjypywyjyvyVyqypyGy5yXycyYy8yU', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='proraMaXaaaAadaBaAaXauamapaGaEahadaRaOaDac', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='skuFMFMZMyMyMnMEMOM7MIMQMoMOMfMlMbMFMtMjMX', max_length=50),
        ),
    ]
