# Generated by Django 5.0.4 on 2024-05-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cartorder_sku_alter_admin_aid_alter_category_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admYDLDcDfDDDoDgDBDQDEDyDgDSDQDtD3DgDSDIDH', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=models.CharField(default='SKUvZiZUZ0ZBZpZ9ZqZHZPZCZiZUZXZYZMZiZX', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catppCpmpHpBpUpMpfpKp6pMpypmpopJpUpfpApqpw', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='prokzdzGzjzzzczMzWzSzlzaztzdzIzTzszszIzvz9', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='skuqpgpvpGpTpppapTpcp1prpBp3pEptpBpJp3', max_length=30),
        ),
    ]
