# Generated by Django 5.0.4 on 2024-05-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_admin_aid_alter_cartorder_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='adm9kAkqkDk2k2kUkxkikaktkTkak7kokxkJksk7kc', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=models.CharField(default='SKUDKkKyKtKwKEKhK6KJKLKYKbKdKUKqKcKVKc', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='cat8bcbEbob3bybHbKb6bnbzbxbcbBbybRbpbybybX', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='proLhwhQhjhuhPhYhdhYhwhkh7hghbhZhihMhWhPhK', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='skuONxNZNZNDN9NWNANtNtN8NbNsNmNYNeNANz', max_length=30),
        ),
    ]
