# Generated by Django 5.0.4 on 2024-05-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_admin_aid_alter_cartorder_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admjRZR2R0RwRbRMRzRsRTRORTRcRSRCR1RqRwRxRo', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=models.CharField(default='SKUiaTaiaMapa7aGa6ava9aMaoaWaZaYaqacaU', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catIDZDMDkDTDrDuDCDwDcDODVDyDmDGDEDuDhDcD6', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='proMumuxuhuPuLuJuKutuzuVuNuCuxu7ueufuAuxu6', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='sku5PfPVPaPdPKPHPbPCP9PhPbPhPKPFPtP1PP', max_length=30),
        ),
    ]
