# Generated by Django 5.0.4 on 2024-05-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_admin_aid_alter_cartorder_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admanknFnqnpnunJnonYnInSnbnanen5nzn1nVnVnV', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=models.CharField(default='SKUhDND4DpDCDXDNDODgDcDlDPDpDnDeDkD4Dy', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catWAHAKA6AMAKA8ALAIAnAgA0A8AvATAkARAzAfAf', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='pro2w2wew0wBw1wbwMwPwOwJw2wywzwFwQwvwSwFwP', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='skusSyStSdSYSZSJSqSxSESwSGS0ScS6SnSWSB', max_length=30),
        ),
    ]
