# Generated by Django 5.0.4 on 2024-05-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_product_tags_alter_admin_aid_alter_cartorder_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admhy6yAyRyRyoyEyryTy5yhy7y1yyyryCyyyZyKyP', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=models.CharField(default='SKUijBjyjcjMjpjfjTjtj5jWj2jejqj7jUjQjc', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='catkPyPePNPrPHP0PcPMPyPEP0P0PfPYPBPlPCPkP9', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='proMaoaGa0aIaaaNaKapaYaGa1araYaqaXalacaoaz', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='sku5vRvUvfvovEvuvCvmvOvyvtvVvivAvdvsvN', max_length=30),
        ),
    ]
