# Generated by Django 5.0.6 on 2024-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_product_tags_alter_admin_aid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.CharField(default='admuIqIMIqIOIxIPIcIhIcICIEI3IHIXI5IBIfI3I7', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=models.CharField(default='SKUxtwtntNtStgt1tFt4tNt2t7tOt1tGtAtStH', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default='cat0cpclcecPc4cHcWcdcZcEcccjcecbcKcvckcicg', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default='proABrBuBqB0BbBqB1BOBEBBBFBbBfBsBsB9BxBCBM', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='sku4JLJCJtJKJeJkJdJCJaJZJ5JQJtJ3JPJRJK', max_length=30),
        ),
    ]
