# Generated by Django 5.0.6 on 2024-05-11 15:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_admin_aid_alter_admin_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
