# Generated by Django 5.0.6 on 2024-05-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_cartorder_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
