# Generated by Django 5.0.6 on 2024-05-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, default='This is the product', null=True),
        ),
    ]
