# Generated by Django 5.0.6 on 2024-05-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
