# Generated by Django 5.0.6 on 2024-05-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_productreview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
