# Generated by Django 5.0.6 on 2024-05-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='price',
            new_name='total_price',
        ),
    ]
