# Generated by Django 5.0.6 on 2024-05-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_rename_price_cartorder_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='product_status',
            new_name='order_status',
        ),
    ]
