# Generated by Django 5.0.6 on 2024-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_cartorder_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
