# Generated by Django 5.0.6 on 2024-05-23 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
