# Generated by Django 5.0.6 on 2024-05-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_cartorder_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='deals',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
