# Generated by Django 5.0.6 on 2024-05-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_rename_featured_product_deals_remove_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='state',
        ),
    ]
