# Generated by Django 5.0.6 on 2024-05-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_cartorder_cp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
