# Generated by Django 5.0.6 on 2024-06-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cp',
        ),
    ]
