# Generated by Django 5.0.6 on 2024-06-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_address_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
