# Generated by Django 5.0.6 on 2024-05-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
