# Generated by Django 5.0.6 on 2024-05-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
