# Generated by Django 5.0.6 on 2024-05-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_remove_profile_bio_alter_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
